name: Build linux kernel

on:
  workflow_call:
    inputs:
      make_release:
        description: 'Whether to create a release with the built kernel'
        required: true
        type: boolean
        default: false

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: read

    container:
      image: ghcr.io/truthdb/truthdb-installer-kernel-builder-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    env:
      KERNEL_VERSION: 6.12
      KERNEL_CONFIG: truthdb-installer-kernel.config
      KERNEL_TARBALL_SHA256: b1a2562be56e42afb3f8489d4c2a7ac472ac23098f1ef1c1e40da601f54625eb

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Fetch kernel source
        run: |
          mkdir -p kernel-src
          cd kernel-src
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          echo "${KERNEL_TARBALL_SHA256}  linux-${KERNEL_VERSION}.tar.xz" | sha256sum -c -
          tar xf linux-${KERNEL_VERSION}.tar.xz --strip-components=1

      - name: Apply TruthDB installer config
        run: |
          cd kernel-src
          cp ../${KERNEL_CONFIG} .config
          make olddefconfig

      - name: Build kernel
        run: |
          cd kernel-src
          make -j"$(nproc)"

      - name: Build installer executable
        run: |
          cd installer
          cargo build --release

      - name: Prepare EFI kernel binary
        if: ${{ inputs.make_release }}
        run: |
          mkdir -p dist
          cp kernel-src/arch/x86/boot/bzImage dist/BOOTX64.EFI
          cp installer/target/release/truthdb-installer dist/truthdb-installer

      - name: Upload artifact
        if: ${{ inputs.make_release }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: truthdb-installer-kernel-${{ github.sha }}
          path: |
            dist/BOOTX64.EFI
            dist/truthdb-installer
